name: Spring Boot CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Maven
        run: mvn clean package

      # 镜像名称 在当前目录
      - name: Build Docker image
        run: docker build -t my-springboot-app .
        
      - name: Save Docker image
        run: docker save my-springboot-app > my-springboot-app.tar

      - name: Copy Docker image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "my-springboot-app.tar"
          target: "./temp"

      - name: Load Docker image on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: docker load < ./temp/my-springboot-app.tar

        
          
    

      
